### ISSUE TITLE
How do you use this to test GUI apps on Travis CI?

### ISSUE THREAD

**Issue by probonopd** [paulcbetts/xvfb-maybe#2]
How do you use this to test GUI apps on Travis CI? I would need to start an GUI app, but then what? In order to find out the exit status, I would at least need a way to quit the application under test.

**Comment by uuf6429** [comment]
![image](https://cloud.githubusercontent.com/assets/230049/25065706/5d0668f6-2214-11e7-82cc-76a0e7476e46.png)

As you can see above, I ran `htop` via `xvfb-maybe`. With the right conditions, it will spawn `xvfb-run` which spawns both an xvfb server and your desired process.

Using simple process execution routines, you should get access to `xvfb-maybe`'s PID (626 in this case). If you terminate this process, the child processes should also stop.

To get the PID of your GUI app, it's definitely possible but it depends on your setup (even in bash).

**Comment by probonopd** [comment]
Thanks for the explanation @uuf6429
